name = "ReportMetrics"
uuid = "c1654acf-408b-4272-96ce-66c258df8a6c"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.2.2"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"

[compat]
Coverage = "1.4"
PrettyTables = "1.3"
julia = "1"
